### PR TITLE
fix: toNano

### PR DESCRIPTION
**Pull request by sergeiavoroshilov**
Using small numbers (< 0) in the toNano function. Just convert it to string before parsing

### CODE REVIEW

**Comment by dvlkv** [comment]
Thank you! Can you please provide tests covering this case?

**Comment by sergeiavoroshilov** [comment]
@dvlkv 
Tests added

**Review by dvlkv — APPROVED** [review]

**Comment by dvlkv** [comment]
@sergeiavoroshilov can you please cover edge cases, especially:

- NaN
- -0
- Infinity
- -Infinity

**Comment by turtletongue** [comment]
It seems like toNano still can't parse a string with number in scientific notation (1e-7 for example)

**Review by dvlkv — APPROVED** [review]

**Pull request merged**
